#!/bin/bash

set -u

template_dir="/usr/local/share/githooks-templatedir"
git config --global init.templatedir "${template_dir}"

template_hooks_dir="${template_dir}/hooks"

mkdir -p ${template_hooks_dir}

if [ -d "/usr/share/git-core" ]; then
  git_core_dir="/usr/share/git-core" # Linux location
elif [ -d "/usr/local/share/git-core" ]; then
  git_core_dir="/usr/local/share/git-core" # OSX location
else
  echo "Could not find git-core templates dir"
fi

for sample_hook in $(ls "${git_core_dir}/templates/hooks"); do
  hook="${template_hooks_dir}/$(basename ${sample_hook} '.sample')" 
  cat <<EOF > ${hook}
#!/usr/bin/env bash
git-hooks run "\$0" "\$@"
EOF
  chmod 755 ${hook}
done
